CREATE DATABASE biblioteca;
USE biblioteca;
CREATE TABLE usuarios (
  id_usuario INT4 NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre_usuario VARCHAR (110) NOT NULL,
  identificacion_usuario VARCHAR (50) NOT NULL UNIQUE,
  correo VARCHAR (110) DEFAULT NULL UNIQUE,
  telefono VARCHAR (30) DEFAULT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE libros (
  isbn VARCHAR (20) NOT NULL PRIMARY KEY,
  titulo VARCHAR (80) NOT NULL,
  año_publicacion YEAR DEFAULT NULL,
  autor VARCHAR (150) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE prestamos (
  id_prestamo INT4 NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_usuario INT4,
  isbn VARCHAR (20),
  fecha_prestamo DATE NOT NULL,
  fecha_devolucion DATE DEFAULT NULL,
  estado ENUM ('entregado', 'retrasado', 'activo') DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (isbn) REFERENCES libros(isbn) ON DELETE SET NULL ON UPDATE CASCADE 
);